# Generated by Django 3.2 on 2022-11-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageapp', '0002_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='headline',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
