# Generated by Django 3.2 on 2022-10-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='desctiption',
            field=models.TextField(blank=True),
        ),
    ]
