# Generated by Django 3.2 on 2022-10-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioapp', '0002_article_desctiption'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
