# Generated by Django 3.2 on 2022-10-22 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioapp', '0004_article_typ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='typ',
            field=models.CharField(choices=[('AR', 'Статья  в журнале'), ('BK', 'Книга')], default='AR', max_length=2, verbose_name='Тип публикации'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biblioapp.author'),
        ),
    ]
