# Generated by Django 3.2 on 2022-10-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioapp', '0008_auto_20221022_0751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reader',
        ),
        migrations.RemoveField(
            model_name='author',
            name='address',
        ),
        migrations.RemoveField(
            model_name='author',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='author',
            name='dirth_day',
        ),
        migrations.AddField(
            model_name='journal',
            name='impact_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='quartile',
            field=models.CharField(choices=[('Q1', 'Первый квартиль'), ('Q2', 'Второй квартиль'), ('Q3', 'Третий квартиль'), ('Q4', 'Четверты квартиль')], default='Q4', max_length=2),
        ),
    ]
