# Generated by Django 3.2 on 2022-10-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioapp', '0009_auto_20221026_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='doi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
