# Generated by Django 3.2 on 2022-10-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioapp', '0010_article_doi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='data',
            new_name='date',
        ),
    ]
