# Generated by Django 3.2 on 2022-10-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioapp', '0012_article_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='referens',
            field=models.ManyToManyField(to='biblioapp.Article'),
        ),
    ]
