# Generated by Django 3.2 on 2022-11-09 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioapp', '0013_article_referens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(to='biblioapp.Author', verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='article',
            name='desctiption',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='article',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biblioapp.journal', verbose_name='Журнал'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Заголовок стати'),
        ),
        migrations.AlterField(
            model_name='article',
            name='referens',
            field=models.ManyToManyField(to='biblioapp.Article', verbose_name='Ссылки'),
        ),
    ]
