# Generated by Django 3.2 on 2022-11-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioapp', '0015_author_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('view_all_article', 'Может смотреть все статиь'),)},
        ),
    ]
