# Generated by Django 3.2 on 2022-11-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioapp', '0016_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pages',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='volume',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='year',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
