# Generated by Django 3.2 on 2022-11-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioapp', '0017_auto_20221126_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='referens',
            field=models.ManyToManyField(blank=True, to='biblioapp.Article', verbose_name='Ссылки'),
        ),
    ]
