# Generated by Django 3.2 on 2022-12-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioapp', '0019_auto_20221203_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='addition_info',
            field=models.JSONField(blank=True, default={}),
        ),
        migrations.AddField(
            model_name='articletype',
            name='excentions',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
